### ISSUE TITLE
File tab window is right click enabled but it does nothing

### ISSUE THREAD

**Issue by vasholotl** [RogerCrocker/BadaBib#8] opened 2022-05-19 05:13 UTC
It's possible to right click in the file tab area which brings up a little popup that does nothing.

![Screenshot from Screencast from 05-18-2022 10:09:17 PM webm - 1](https://user-images.githubusercontent.com/48813136/169213264-14f39768-079f-4fc3-a817-c8f0825bc2b2.png)

**Comment by RogerCrocker** [comment] 2022-05-19 23:07
Hi, thanks for the bug report. 

I can reproduce this problem. Funnily, the right click works fine right after Bada Bib! was opened. But it stops working as soon as a file is added or removed. I can see some low-level GTK errors in this case, which makes me think that this might actually be a GTK issue. I'll see if I can reproduce this in a minimal application and maybe file a bug report for GTK.

**Comment by vasholotl** [comment] 2022-05-19 23:17
You're right! It does work after Baba Bib! is first opened. I'm not an app developer sadly so I don't know GTK at all but I'm happy to help test things out.

**Comment by RogerCrocker** [comment] 2022-05-19 23:20
Thanks! I'll update this issue if I find out more.

**Comment by RogerCrocker** [comment] 2022-08-10 01:54
Hi, and sorry for the long delay. Since the recent 0.8.0 release Bada Bib! uses Adwaita tabs instead of a GTK notebook. For now the right-click menu is disabled, so at least there is no longer an empty popup. I'll close this issue, but I would like to bring back the option to show a list of open files in some form...

**Closed as completed by RogerCrocker** 2022-08-10 01:54 UTC
